include ../include_top.mk

# calls:
INCLUDES   = ${INCLUDES_COMMON}
CFLAGS     = ${CFLAGS_COMMON} ${INCLUDES}
LDFLAGS    = ${LDFLAGS_COMMON}
EXECUTABLE = ../../bin/gmshToTobj

SOURCES    = gmshToTobj.cpp MshLoader.cpp

include ../include_bottom.mk
